export * from "./models/auth";
import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { users } from "./models/auth";

export const expenses = pgTable("expenses", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(), // We manually handle the relation for simplicity or use references
  amount: integer("amount").notNull(), // Stored in cents
  category: text("category").notNull(),
  description: text("description").notNull(),
  date: timestamp("date").notNull().defaultNow(),
  source: text("source").notNull().default("manual"), // 'manual', 'ai_parsed'
});

export const insertExpenseSchema = createInsertSchema(expenses).omit({
  id: true,
  userId: true,
});

export type Expense = typeof expenses.$inferSelect;
export type InsertExpense = z.infer<typeof insertExpenseSchema>;

// Request Types
export type CreateExpenseRequest = InsertExpense;
export type UpdateExpenseRequest = Partial<InsertExpense>;

// AI Parsing
export const parseExpenseSchema = z.object({
  text: z.string().min(1),
});
export type ParseExpenseRequest = z.infer<typeof parseExpenseSchema>;

// Analysis Response
export type CategoryAnalysis = {
  category: string;
  total: number; // in cents
  percentage: number;
};

export type MonthlyAnalysisResponse = {
  totalSpend: number;
  byCategory: CategoryAnalysis[];
  recentTrend: number[]; // Last 7 days or similar
  aiInsights: string[]; // Textual insights generated by AI
};
